CREATE TABLE IF NOT EXISTS JOIN_POINT (
  KKS VARCHAR(48) PRIMARY KEY NOT NULL,
  X   DOUBLE,
  Y   DOUBLE,
  Z   DOUBLE
);

CREATE TABLE IF NOT EXISTS JOURNAL (
  KKS  VARCHAR(48) PRIMARY KEY NOT NULL,
  FILE LONGBLOB
);

CREATE TABLE IF NOT EXISTS ROUTE_TYPE (
  MARKER VARCHAR(24) PRIMARY KEY NOT NULL,
  NAME   VARCHAR(128)
);

CREATE TABLE IF NOT EXISTS EQUIPMENT (
  FULL_NAME      VARCHAR(128) PRIMARY KEY NOT NULL,
  KKS            VARCHAR(48),
  ADD_LENGTH     INT,
  X              DOUBLE,
  Y              DOUBLE,
  Z              DOUBLE,
  JOIN_POINT_KKS VARCHAR(48),
  FOREIGN KEY (JOIN_POINT_KKS) REFERENCES JOIN_POINT (KKS)
);

CREATE TABLE IF NOT EXISTS ROUTE (
  KKS                   VARCHAR(48) PRIMARY KEY NOT NULL,
  ROUTE_TYPE_MARKER     VARCHAR(24),
  LENGTH                DOUBLE,
  HEIGHT                DOUBLE,
  SHELVES_COUNT         INT,
  FIRST_JOIN_POINT_KKS  VARCHAR(48),
  SECOND_JOIN_POINT_KKS VARCHAR(48),
  FOREIGN KEY (FIRST_JOIN_POINT_KKS) REFERENCES JOIN_POINT (KKS),
  FOREIGN KEY (SECOND_JOIN_POINT_KKS) REFERENCES JOIN_POINT (KKS),
  FOREIGN KEY (ROUTE_TYPE_MARKER) REFERENCES ROUTE_TYPE (MARKER)
);

CREATE TABLE IF NOT EXISTS LINE (
  ID                   INT     AUTO_INCREMENT PRIMARY KEY,
  START_JOIN_POINT_KKS VARCHAR(48),
  END_JOIN_POINT_KKS   VARCHAR(48),
  TRACED               BOOLEAN DEFAULT FALSE,
  FOREIGN KEY (START_JOIN_POINT_KKS) REFERENCES JOIN_POINT (KKS),
  FOREIGN KEY (END_JOIN_POINT_KKS) REFERENCES JOIN_POINT (KKS)
);

CREATE TABLE IF NOT EXISTS CABLE (
  KKS                  VARCHAR(48) PRIMARY KEY NOT NULL,
  JOURNAL_KKS          VARCHAR(48) NOT NULL,
  NUMBER_IN_JOURNAL    INT,
  TYPE                 VARCHAR(48),
  DIMENSIONS           VARCHAR(48),
  EQUIPMENT_START_NAME VARCHAR(128),
  EQUIPMENT_END_NAME   VARCHAR(128),
  RESERVING            VARCHAR(48),
  LENGTH               INT,
  FOREIGN KEY (EQUIPMENT_START_NAME) REFERENCES EQUIPMENT (FULL_NAME),
  FOREIGN KEY (EQUIPMENT_END_NAME) REFERENCES EQUIPMENT (FULL_NAME),
  FOREIGN KEY (JOURNAL_KKS) REFERENCES JOURNAL (KKS)
);

CREATE TABLE IF NOT EXISTS LINES_ROUTES (
  ROUTE_KKS VARCHAR(48) NOT NULL,
  LINE_ID   INT         NOT NULL,
  FOREIGN KEY (ROUTE_KKS) REFERENCES ROUTE (KKS),
  FOREIGN KEY (LINE_ID) REFERENCES LINE (ID),
  UNIQUE (LINE_ID, ROUTE_KKS)
);


